# Generated by Django 4.0.6 on 2022-07-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_productapp_published_alter_productapp_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
